//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTagMapping
    {
        public int AID { get; set; }
        public int TID { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
