//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.ArticleTagMapping = new HashSet<ArticleTagMapping>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int AID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ViewNum { get; set; }
        public Nullable<int> CommentNum { get; set; }
        public int CID { get; set; }
        public int UID { get; set; }
        public string Summery { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ArticleTagMapping> ArticleTagMapping { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
