//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<int> AID { get; set; }
        public Nullable<int> PID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UID { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual Users Users { get; set; }
    }
}
