//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public Photos()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int PID { get; set; }
        public string PhotoName { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int AlbumID { get; set; }
        public int UID { get; set; }
        public string Thumbnailw { get; set; }
        public Nullable<int> Thumbnailw_width { get; set; }
        public Nullable<int> Thumbnailw_height { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Users Users { get; set; }
    }
}
