//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Albums = new HashSet<Albums>();
            this.Articles = new HashSet<Articles>();
            this.Categories = new HashSet<Categories>();
            this.Comments = new HashSet<Comments>();
            this.Photos = new HashSet<Photos>();
            this.Tags = new HashSet<Tags>();
        }
    
        public int UID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string HeadPic { get; set; }
        public string SelfIntro { get; set; }
        public System.DateTime RegTime { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Mid { get; set; }
        public int UserRoleID { get; set; }
    
        public virtual ICollection<Albums> Albums { get; set; }
        public virtual ICollection<Articles> Articles { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
